apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-pod-dev
  labels:
    app: nginx-pod-dev
spec:
  project: default
  destination:
    namespace: nginx-pod-dev
    name: in-cluster
  source:
    repoURL: https://github.com/wsslhllmn/itq-workshop-argocd.git
    targetRevision: main
    path: ./k8s-resources/nginx-pod/dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
