apiVersion: v1
kind: Secret
metadata:
  name: local-dev
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/wsslhllmn/itq-workshop-argocd.git
