apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: developer
spec:
  description: ArgoCD project for developer
  destinations:
    - namespace: 'developer*'
      server: '*'
  sourceRepos:
    - '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
